name: Release 

on:


  workflow_dispatch:
    inputs:
      version:
        description: 'Log level'
        required: true

      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:

  deploy-to-prod:
    name: Deploy in prod
    runs-on: ubuntu-latest    
    environment:
      name: "prod"
    steps:
    - name: Download Artifact
      run: echo "Downloading..."
    - name: Deploy
      run: echo "Deploying..."      
