name: Hotfix 


on:
  push:
    branches:
      - hotfix

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Initialize
      run: echo "Initializing..."
    
    - name: Checkout SCM
      run: echo "Initializing..."

    - name: Build
      run: echo "Building..."

    - name: Integration tests
      run: echo "Integration tests..."
      
  deploy-to-stage:
    name: Deploy in stage
    runs-on: ubuntu-latest    
    needs: build
    environment:
      name: "stage"
    steps:
    - name: Download Artifact
      run: echo "Downloading..."
    - name: Deploy
      run: echo "Deploying..."
      
  deploy-to-prod:
    name: Deploy in prod
    runs-on: ubuntu-latest    
    needs: deploy-to-stage
    environment:
      name: "prod"
    steps:
    - name: Download Artifact
      run: echo "Downloading..."
    - name: Deploy
      run: echo "Deploying..."      
